accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('myaccount/', views.my_account, name='myaccount'),
]

food/urls.py
""" File dedicated for urls in food application """
from django.urls import path
from . import views


app_name = 'food'
urlpatterns = [
    path('results/', views.get, name='result_page'),
    path('food/<int:food_id>/', views.food_page, name='food_detail'),
    path('ajax/', views.favorite, name='favorite'),
    path('myfoods/', views.my_foods, name='foods_saved')
]

pur_beurre/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('welcome.urls')),
    path('', include('accounts.urls')),
    path('', include('food.urls')),
    path('admin/', admin.site.urls),
]

welcome/urls.py
from django.urls import path

from welcome import views

app_name = 'welcome'
urlpatterns = [
    path('', views.index, name='home'),
    path('mentions-legales/', views.legal, name='legalnotice'),
    path('contact', views.contact, name='contact')
]

accounts/models.py
from django.db import models

# Create your models here.

food/models.py
""" models file dedicated for food application """
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    """ Create Category model """
    name = models.CharField(max_length=200)


class Food(models.Model):
    """ Create Food model """
    name = models.CharField(max_length=200)
    nutriscore = models.CharField(max_length=1)
    url = models.URLField(max_length=250)
    url_picture = models.URLField(max_length=250)
    fat_100g = models.DecimalField(max_digits=5, decimal_places=2)
    saturated_fat_100g = models.DecimalField(max_digits=5, decimal_places=2)
    sugars_100g = models.DecimalField(max_digits=5, decimal_places=2)
    salt_100g = models.DecimalField(max_digits=5, decimal_places=2)
    fat_level = models.CharField(max_length=10)
    salt_level = models.CharField(max_length=10)
    saturated_fat_level = models.CharField(max_length=10)
    sugars_level = models.CharField(max_length=10)
    last_modified = models.DateField()
    openff_id = models.BigIntegerField()
    categories = models.ManyToManyField(Category)
    favorite_users = models.ManyToManyField(User, related_name="favorite_foods")

    def get_substitute(self, product_name):
        """ Method which find the substitute of
        the food requested """
        food_requested = Food.objects.filter(name__icontains=product_name)
        if len(food_requested) == 0:
            return False
        name_product = food_requested[0].name
        image = food_requested[0].url_picture
        categories = food_requested[0].categories.all()
        category_id = categories[0].id
        category_get = Category.objects.filter(pk=category_id)
        substitutes_ordered = category_get[0].food_set.all().order_by('nutriscore')
        return [substitutes_ordered, name_product, image]

welcome/models.py
from django.db import models

# Create your models here.

accounts/forms.py
""" File used to create and personnalize the UserRegisterForm """
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    """ Inherited from UserCreationForm
    to personnalize the registration form """
    email = forms.EmailField()
    first_name = forms.CharField(max_length=30, label="Prénom")
    last_name = forms.CharField(max_length=30, label="Nom")

    class Meta:
        """ Define the order of Fields """
        model = User
        fields = ['username',
                  'first_name',
                  'last_name',
                  'email',
                  'password1',
                  'password2']

welcome/forms.py
from django import forms

class SearchForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Produit'}), label='', max_length=100)

accounts/views.py
""" Views.py dedicated for views , in 'accounts' application """
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from accounts.forms import UserRegisterForm


def register(request):
    """ Method for welcome page """
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('welcome:home')
    else:
        form = UserRegisterForm()
    return render(request, 'accounts/create_account.html', {'form': form})


@login_required
def my_account(request):
    """ Method for my_account page"""
    return render(request, 'accounts/my_account.html')

food/views.py
""" View file for food application """
import json
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from django.views import View
from food.models import Food


def food_page(request, food_id):
    "function for food_page"
    article = Food.objects.get(pk=food_id)
    return render(request, 'food/food_details.html', {'article': article})



def get(request):
    """ dedicated for get methods """
    food = Food()
    template_name = 'food/search_page.html'
    query = request.GET.get('search')
    list = food.get_substitute(query)
    if list is False:
        return render(request, template_name, {'nofood': "Pas d'aliment trouvé"})
    substitutes_list = list[0]
    paginator = Paginator(substitutes_list, 6)
    page = request.GET.get('page')
    substitutes_list = paginator.get_page(page)
    args = ({'food_search': list[1],
                'articles_found': substitutes_list,
                'image': list[2],
                'page': page,
                'query': query})
    return render(request, template_name, args)


@require_POST
def favorite(request):
    """ Receive the ajax request to add favorite foods"""
    if request.is_ajax():
        food_id = json.loads(request.body.decode('utf-8')).get('id')
        food = Food.objects.get(pk=food_id)
        current_user = request.user
        user = User.objects.get(pk=current_user.id)
        food.favorite_users.add(user.id)
        data = "le produit a été enregistré"
    return HttpResponse(data)

@login_required
def my_foods(request):
    """ display the page my_foods """
    foods_saved = request.user.favorite_foods.all()
    paginator = Paginator(foods_saved, 6)
    page = request.GET.get('page')
    foods_saved = paginator.get_page(page)
    return render(request, 'food/my_foods.html', {'foods_saved': foods_saved})

welcome/views.py
""" Views associated to the Welcome application """
from django.shortcuts import render, redirect, reverse
from welcome.forms import SearchForm


def index(request):
    """ Method associated to the homepage """
    template_name = 'welcome/index.html'
    form = SearchForm()
    return render(request, template_name, {'form': form})


def legal(request):
    """ Method associated to the legal_notice page """
    return render(request, 'welcome/legalnotice.html')

def contact(request):
    """ Method to go directly on contact section"""
    return redirect(reverse('welcome:home') + '#contact')

accounts/templates/accounts/create_account.html
{% extends 'welcome/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<link href="{% static 'accounts/css/style.css' %}" rel="stylesheet">
  <!-- Masthead -->
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center ">
        <div class="col-lg-10 align-self-start">
          <h2 class="text-uppercase text-white font-weight-bold center">Créez votre compte</h2>
          <hr class="divider my-4">
        </div>
        <div class="col-lg-10 align-content-justify">
          <form method="POST">
            {% csrf_token %}
                {{ form|crispy}}
            <button class="btn btn-outline-info" type="submit"> S'inscrire</button>
          </form>
        </div>
      </div>
    </div>
  </header>

{% endblock %}

accounts/templates/accounts/login.html
{% extends "welcome/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<link href="{% static 'accounts/css/style.css' %}" rel="stylesheet">
  <!-- Masthead -->
  <header class="masthead">
    <div class="container h-100">
        <div class="col-lg-10 align-self-start">
          <h2 class="text-uppercase text-white font-weight-bold center">Se connecter</h2>
          <hr class="divider my-4">
        </div>
        <div class="col-lg-10 align-content-center">
          <form method="POST">
            {% csrf_token %}
                {{ form|crispy }}
            <button class="btn btn-outline-info" type="submit">Se connecter</button>
          </form>
        </div>
    </div>
  </header>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'welcome/base.html' %}
{% load static %}

{% block content %}
  <link href="{% static 'accounts/css/style.css' %}" rel="stylesheet">
  <!-- Masthead -->
  <header class="masthead">
    <div class="container h-100">
          <h2 class="text-uppercase text-white font-weight-bold center">Vous êtes déconnecté</h2>
        </div>
  </header>

{% endblock %}

accounts/templates/accounts/my_account.html
{% extends "welcome/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<link href="{% static 'accounts/css/style.css' %}" rel="stylesheet">
  <!-- Masthead -->
  <header class="masthead header-foodsearch h-30">
    <div class="container h-100">
      <div class="row h-50 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end profile">
            <p class="center"> Bonjour {{ user.first_name }} ! </p>
          <h1 class="text-uppercase text-white font-weight-bold"></h1>
          <hr class="divider my-4">
        </div>
      </div>
    </div>
  </header>

  <section class="h-50">
    <div class="container h-100">
      <div class="col-12 center text-black h-100">
        <p class="margintop"> {{ user.email }} </p>
      </div>
    </div>
  </section>

{% endblock %}

food/templates/food/food_details.html
{% extends "welcome/base.html" %}
{% load static %}

{% block content %}
<link href="{% static 'accounts/css/style.css' %}" rel="stylesheet">
  <!-- Masthead -->
  <header class=" masthead header-foodsearch color" style="background-image: url({{ article.url_picture }});">
    <div class="container h-100">
      <div class="row align-items-center h-100">
        <div class="col-12 text-center">
            <h4 class="text-white font-weight-bold center">{{ article.name }}</h4>
        </div>
      </div>
    </div>
  </header>

  <section>
    <div class= "container h-30 margin-top">
      <div class = "row">
        <div class="col-lg-6 col-sm-12">
          <h4 class="font-weight-bold margin-text margin-top">Nutriscore</h4>
          <img class="" src="{% get_static_prefix %}food/img/nutriscores/{{ article.nutriscore }}.jpg"/>
        </div>
          <div class="col-lg-6 col-sm-12">
            <h4 class="font-weight-bold margin-top">Répères nutritionnels pour 100g</h4>
            <ul>
                <li> {{ article.fat_100g }}g Matières grasses/Lipides </li>
                <li> {{ article.saturated_fat_100g }} g Acides gras saturés </li>
                <li> {{ article.sugars_100g }}g Sucres </li>
                <li> {{ article.salt_100g }}g Sel </li>
              </ul>
          </div>
      </div>
    </div>
  </section>

  <section>
    <div class= "row">
      <div class= "col-12 center margin-bottom">
          <a href="{{ article.url }}">Voir la fiche d'OpenFoodFacts</a>
      </div>
    </div>
  </section>
{% endblock %}

food/templates/food/my_foods.html
{% extends "welcome/base.html" %}
{% load static %}

{% block content %}
<link href="{% static 'accounts/css/style.css' %}" rel="stylesheet">
  <!-- Masthead -->
  <header class=" masthead header-foodsearch color">
    <div class="container h-100">
      <div class="row align-items-center h-100">
        <div class="col-12 text-center">
            <h3 class="text-white font-weight-bold center">Vos Aliments favoris</h3>
        </div>
      </div>
    </div>
  </header>

  <h4 class="text-black font-weight-bold center">Voici les éléments que vous avez sauvegardé !</h4>
  <div class="row justify-content">
  <div class="col-lg-10 mx-auto row align-items-center card-body ">
      {% for food in foods_saved %}
          <div class="mx-auto article col-lg-4 col-sm-12 text-black center-content margin-top">
              <a href={% url 'food:food_detail' food_id=food.pk %}><img class= "article-img align-items-center mx-auto" src="{{ food.url_picture }}"></a></br>
              <p class="article-name center"> {{ food.name }} </p>
              <p class="article-nutriscore top-right"> {{ food.nutriscore }} </p>
          </div>
      {% endfor %}
        </div>
      </div>

  <div class="pagination text-black">
    <span class="step-links">
      {% if foods_saved.has_previous %}
        <a href="?page=1">&laquo; Première page</a>
        <a href="?page={{ foods_saved.previous_page_number }}">Page précédente</a>
      {% endif %}

      <span class="current">
        Page {{ foods_saved.number }} of {{ foods_saved.paginator.num_pages }}.
      </span>

      {% if foods_saved.has_next %}
            <a href="?page={{ foods_saved.next_page_number }}">Page suivante</a>
            <a href="?page={{ foods_saved.paginator.num_pages }}">Dernière &raquo;</a>
        {% endif %}

    </span>
  </div>

{% endblock %}

food/templates/food/search_page.html
{% extends "welcome/base.html" %}
{% load static %}

{% block content %}
<link href="{% static 'accounts/css/style.css' %}" rel="stylesheet">
  <!-- Masthead -->
  <header class=" masthead header-foodsearch color" style="background-image: url({{ image }});">
    <div class="container h-100">
      <div class="row align-items-center h-100">
        <div class="col-12 text-center">
            <h4 class="text-white font-weight-bold center">{{ food_search }} </h4>
        </div>
      </div>
    </div>
  </header>

  <h3 class="text-black font-weight-bold center"> Vous pouvez remplacer cet aliment par :</h3>
  <p> <h3 class="center"> {{ nofood }} </h3> </p>
  <div class="row justify-content">
  <div class="col-lg-10 mx-auto row align-items-center card-body ">
      {% for article in articles_found %}
          <div class="mx-auto article col-lg-4 col-sm-12 text-black center-content margin-top">
              <a href={% url 'food:food_detail' food_id=article.id %} ><img class= "article-img align-items-center mx-auto" src="{{ article.url_picture }}"></a></br>
              <p class="article-name center"> {{ article.name }} </p>
              <p class="article-nutriscore top-right"> {{ article.nutriscore }} </p>
              {% if user.is_authenticated %}
              <div class="save_func">
                <form class="center">
                  {% csrf_token %}
                  <input type="hidden" name="food_id" value="{{ article.pk }}">
                  <button class="btn btn-primary save_food" data-food-id="{{ article.pk }}">
                    <i class="far fa-save"></i> Sauvegarder
                  </button>
                </form>
              </div>
              {% endif %}
          </div>
      {% endfor %}
        </div>
      </div>

  <div class="pagination text-black">
    <span class="step-links">
      {% if articles_found.has_previous %}
        <a href="?search={{ query }}&page=1">&laquo; Première page</a>
        <a href="?search={{ query }}&page={{ articles_found.previous_page_number }}">Page précédente</a>
      {% endif %}

      <span class="current">
        Page {{ articles_found.number }} of {{ articles_found.paginator.num_pages }}.
      </span>

      {% if articles_found.has_next %}
            <a href="?search={{ query }}&page={{ articles_found.next_page_number }}">Page suivante</a>
            <a href="?search={{ query }}&page={{ articles_found.paginator.num_pages }}">Dernière &raquo;</a>
        {% endif %}

    </span>
  </div>

  <script src="{% static 'food/js/ajax_post.js' %}"></script>
  <script src="{% static 'food/js/save.js' %}"></script>

{% endblock %}

welcome/templates/welcome/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Pur Beurre</title>

  <!-- Font Awesome Icons -->
  <link href="{% static 'welcome/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Favicon -->
  <link rel="shortcut icon" type="image/png" href="{% static 'welcome/img/favicon.png' %}"/>

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel='stylesheet' type='text/css'>

  <!-- Plugin CSS -->
  <link href="{% static 'welcome/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link href="{% static 'welcome/css/creative.css' %}" rel="stylesheet">

  <!-- Icones - Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">


</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
      <img class= "logo-pur-beurre" src="{% static 'welcome/img/logo-pur-beurre.png' %}">
      <a class="navbar-brand js-scroll-trigger" href="{% url 'welcome:home' %}">Pur Beurre</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          <li class="nav-item">
            <form action="{% url 'food:result_page' %}" method="GET">
              <input type="text" id="search-navbar" placeholder=" Chercher" name="search">
            </form>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'accounts:myaccount' %}"><img class="logo-navbar" ><i class="fas fa-user fa-2x"></i></a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'accounts:register' %}"><img class="logo-navbar" >Créer un compte</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'food:foods_saved' %}"><img class="logo-navbar carrot" src="{% static 'welcome/img/Carrot.png' %}"></a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'accounts:logout' %}"><img class="logo-navbar"><i class="fas fa-sign-out-alt fa-2x"></i></a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'accounts:login' %}"><img class="logo-navbar">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% block content %}{% endblock %}


  <!-- Footer -->
  <footer class="card-footer bg-light py-5">
    <div class="container">
      <div class="small text-center footer-color">
      <a class="footer-link footer-color" href="{% url 'welcome:legalnotice' %}">Mentions légales </a> -- Copyright &copy; 2019 Pur Beurre --
      <a class="footer-link footer-color" href="{% url 'welcome:contact' %}"> Contact </a>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'welcome/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'welcome/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'welcome/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'welcome/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'welcome/js/creative.min.js' %}"></script>

</body>

</html>

welcome/templates/welcome/index.html
{% extends "welcome/base.html" %}
{% load static %}

{% block content %}
<link href="{% static 'accounts/css/style.css' %}" rel="stylesheet">
  <!-- Masthead -->
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
          <h1 class="text-uppercase text-white font-weight-bold">Du gras, oui, mais de qualité ! </h1>
          <hr class="divider my-4">
        </div>
        <div class="col-lg-8 align-self-baseline">
          <h2 class="text-white-75 font-weight-light mb-5">Trouvez un produit de substitution pour ceux que vous consommez tous les jours.</h2>
          <form action="{% url 'food:result_page' %}" method="GET">
            {{ form }}<input type="submit" class="search-btn" >
          </form>
        </div>
      </div>
    </div>
  </header>

  <!-- About Section -->
  <section class="page-section bg-primary" id="about">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="text-white mt-0">Colette et Remy</h2>
          <hr class="divider light my-4">
          <p class="text-white-50 mb-4">Pur Beurre est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et Rémy, que vous avez déjà certainement rencontrés dans notre excellent restaurant Ratatouille.</p>
          <p class="text-white-50 mb-4"><span class="font-weight-bold">Colette Tatou :</span><span class="font-italic">"Nous aimons tous manger, surtout en France ! Personnellement, une baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. Comme tout le monde, je fais mes courses au supermarché. Mais petit à petit je me suis rendue compte, surtout lorsque nous avons ouvert le restaurant, que je pouvais remplacer les produits aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir Et souvent pour le même prix !"</span></p>
          <p class="text-white-50 mb-4"><span class="font-weight-bold">Remy :</span><span class="font-italic">"Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup me balader, surtout dans les caves et les cuisines. Je connaissais par coeur le contenu des boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments vendus. Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un aliment plus sain, je savais tout de suite où le trouver. L'idée de Pur Beurre était née !"</span></p>
          <a class="" href="#services"><img class="img-colette-remy" src="{% static 'welcome/img/colette-img.png' %}"></a>
          <a class="" href="#services"><img class="img-colette-remy" src="{% static 'welcome/img/remy-img.png' %}"></a>

        </div>
      </div>
    </div>
  </section>

  <!-- Contact Section -->
  <section class="page-section" id="contact">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="mt-0">Contactez-nous !</h2>
          <hr class="divider my-4">
          <p class=" mb-5">Vous rencontrez un soucis sur notre site, ou vous avez des suggestions à nous faire parvenir? N'hésitez pas à nous contacter !</p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 ml-auto text-center">
          <i class="fas fa-phone fa-3x mb-3"></i>
          <div>+33 (1) 123-0123
          </div>
        </div>
        <div class="col-lg-4 mr-auto text-center">
          <i class="fas fa-envelope fa-3x mb-3"></i>
          <!-- Make sure to change the email address in anchor text AND the link below! -->
          <a class="d-block" href="mailto:mail@mail.com">mail@mail.com</a>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

welcome/templates/welcome/legalnotice.html
{% extends "welcome/base.html" %}
{% load static %}

{% block content %}
<link href="{% static 'accounts/css/style.css' %}" rel="stylesheet">
  <!-- Masthead -->
  <header bg-primary >
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
    </div>
    </div>
  </header>

  <!-- About Section -->
  <section class="page-section legal h-80" >
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h2 class="text-black mt-0 center">Mentions légales Pur Beurre</h2>
        <div class="col-12 col-xs-12 margin-top">
        <ul class="notice margin-top">
            <li><b>Entreprise Pur Beurre </b></li>
            <li><b><u>Propriétaires:</u> Remy et Colette Tatou</b></li>
            <li><b><u>Siret:</u> 320773369000</b></li>
            <li><b><u>Coordonnées de l'hébergeur:</u></b><a href="https://www.heroku.com/home">Heroku</a></li>
            <li><b><u>Template Bootstrap par:</u></b><a href="https://startbootstrap.com/">Start Bootstrap</a></li>
            <li><b><u>Icone carotte:</u></b><a href="https://thenounproject.com/term/carrot/29691/">Noun Project</a></li>
            <li><b><u>Icones Font Awesome:</u></b><a href="https://fontawesome.com/">Font Awesome</a></li>
            <li><b><u>Photo de fond par:</u></b><a href="https://unsplash.com/photos/k60JspcBwKE">Kawin Harasai</a></li>
            <li><b><u>Code source:</u></b><a href="https://github.com/Seiph59/Projet-8-Django">Github</a></li>
        </ul>
        </div>
        </div>
      </div>
    </div>
  </section>


{% endblock %}